### ISSUE TITLE
Look For Help

### ISSUE THREAD

**Issue by Bimmer-S** [swagshaw/ASC-CL#1]
![image](https://user-images.githubusercontent.com/109191958/201465742-77e1122d-3981-4791-82ac-77053434b534.png)
Dear Author:
         When I reproduce your code, this error occurs. The online search does not solve this error. Can you help me to check it. Thank You !

**Comment by swagshaw** [comment]
Hello, actually I didn't meet this issue before. But it seems that the object type need to transform. You can print the type of batch_target_dict to check and fix it.

The target should be of type torch.long. Try to call batch_target_dict = batch_target_dict.long() to transform the data type.

Sorry for the late response.

**Comment by Bimmer-S** [comment]
Thank you very much for your reply. I will study it carefully
