### ISSUE TITLE
How to train on a custom dataset

### ISSUE THREAD

**Issue by Sreeni1204** [swagshaw/ASC-CL#2]
I am performing audio classification on a custom dataset. COuld you please provide me some information on training the model on a custom dataset.

**Comment by swagshaw** [comment]
Hi @Sreeni1204 ,

Thanks for your interest in our work. For the custom dataset, you could refer to the `ASC-CL/data/generate_json.py`. I split our dataset there and generate the `metadata.json`. Then you could develop your custom dataset class. In this part, you could refer to the `data_loader.py`. Wish these could help you.

**Comment by Sreeni1204** [comment]
Thank you for the response, will try this out and get back to you
